`r if_else(max_fy == sel_fy, hb, paste0(hb, " ", str_replace(sel_fy, "/", ""), ' {.hidden}'))`
=================================================

```{r summary figures, include=FALSE}

# Expected vs Referrals
ref <- sum(subpage_data$referrals)
exp_rate <- (ref / exp) * 100

# 12 Months Complete
num <- subpage_data %>% filter(ldp %in% c("complete", "exempt")) %>% {sum(.$referrals)}
den <- subpage_data %>% filter(ldp %in% c("complete", "exempt", "fail")) %>% {sum(.$referrals)}
pds_rate <- (num / den) * 100

complete_year <- if_else(max_fy == sel_fy & qt != 4, FALSE, TRUE)

```

Sidebar {.sidebar}
-----------------------------------------------------------------------

### `r hb`
#### Financial Year `r sel_fy`

***

Select Financial Year

<!-- For some reason need '-2' on end of 1819 links - check why this is -->
|     `r paste0("[2019/20](#", hb %>% tolower() %>% str_replace_all(" &", "") %>% str_replace_all(" ", "-"), "-3)")`
|     `r paste0("[2018/19](#", hb %>% tolower() %>% str_replace_all(" &", "") %>% str_replace_all(" ", "-"), "-", "201819)")`
|     `r paste0("[2017/18](#", hb %>% tolower() %>% str_replace_all(" &", "") %>% str_replace_all(" ", "-"), "-", "201718)")`
|     `r paste0("[2016/17](#", hb %>% tolower() %>% str_replace_all(" &", "") %>% str_replace_all(" ", "-"), "-", "201617)")`

***

<!-- Reword this and try and force to bottom of sidebar -->
Please get in touch with any comments, suggestions and feedback: [NSS.ISDDementiaPDS@nhs.net](mailto:NSS.ISDDementiaPDS@nhs.net)


Row
-----------------------------------------------------------------------

### <!-- Management Information Tagline -->

<font size="3"> 
<center> <bold>
<span style="color:red"> 
MANAGEMENT INFORMATION ONLY: NOT FOR ONWARD DISTRIBUTION 
</span> </center> </font> </bold>


Row
----------------------------------------------------------------------

### <!-- Information -->

More information here.


Row
----------------------------------------------------------------------

### Referrals Value Box
```{r Referrals Value Box}
valueBox(ref, 
         icon = "fa-hashtag",
         caption = glue("referrals were made for post-diagnostic support."))
```

`r ifelse(complete_year == TRUE, "### Expected Value Box", "")`
```{r Expected Value Box, include = complete_year}
valueBox(paste0(round_half_up(exp_rate, 1), "%"), 
         icon = "fa-percent",
         caption = glue("of the expected number of diagnoses were ",
                        "referred for post diagnostic support."))
```

### 12 Months Value Box
```{r 12 Months Value Box}
valueBox(paste0(round_half_up(pds_rate, 1), "%"), 
         icon = "fa-percent",
         caption = glue("of those referred for post diagnostic support ",
                        "received 12 months of support."))
```


Row {data-height=500}
----------------------------------------------------------------------

### **Number of Individuals Diagnosed and Referred for PDS** {data-width=800}

```{r Referrals Plot}

plot_referrals(subpage_data, 
               scotland = TRUE,
               quarter = ifelse(max_fy == sel_fy, qt, NA))

```

